### PR TITLE
added compatibility for alpha nodes

### PR DESCRIPTION
**Pull request by UWUplus**
I tried to make the nodes compatible with older the 2.8 version of Blender again, please test this before merging.

### CODE REVIEW

**Comment by UWUplus** [comment]
This pull request is made regarding https://github.com/TheWeirdSquid/Minecraft-Player-Head-Tools/issues/2#issuecomment-851742610

**Comment by DavidBootle** [comment]
Alright, I'll go ahead and merge once I've had the time to test it. Thank you!

**Comment by DavidBootle** [comment]
Ah! I found the issue. It appears that a new node was added to the principled BDSF shader in blender 2.91, the emission strength node. This pushed the alpha node down to index 19, which caused the issue with the nodes. I'll have to either create a version of the add-on for both versions (as 2.83 is LTS), or I'll have to reprogram it to use something other than indexes. I'll look into it.

**Comment by DavidBootle** [comment]
Alright, so it turns out that you can specify the nodes by using dictionary syntax as well, so instead of indexes, you can put the name of the node. This has fixed the issue. Because of this, I'm not going to merge your pull request, but I greatly appreciate your help in figuring this out. I'll create a new release with the fix shortly.

Example for clarity (old on top, new on bottom):
```python
links.new(node_image.outputs[0], node_principled.inputs[0]) # link image color output to color input
links.new(node_image.outputs["Color"], node_principled.inputs["Base Color"]) # link image color output to color input
```

**Comment by DavidBootle** [comment]
The commit that fixed this issue is 459449987da8df95767676c852ab63c3a274fc17.

**Pull request closed without merging**
